let PAGES = [
    'Zebra Sarasa Clip',
    'Uni-Ball Jetstream',
    'Uni-Ball Zento Flow',
    'Pentel Calme',
    'Zebra Sarasa Grand',
    'Zebra BlenU',
    'Tombow Airpress',
    'Pentel Floatune',
    'Uni Jetstream Multipen',
    'Zebra Sarasa Markon',
    'Uni-Ball One F',
    'Uni Kuru Toga Advance',
    'Tombow Monograph Tune',
    'Pentel Graphgear',
    'Tombow Coloured Pencils',
    'Kokuyo Standard B5 Ruled',
    'Kokuto Binder Note',
    'Midori MD A5 Dote Grid',
    'Kokuyo Campus Loose-leaf Ruled',
    'Kokuyo Campus Loose-Leaf Luz Diagram',
    'Kokuyo Campus Loose-Leaf Dote Grid',
    'Kokuyo Gloo Small White',
    'Kokuyo Gloo Medium White',
    'Kokuyo Gloo Small Black',
    'Pentel Ain Eraser',
    'Kokuyo Resare Eraser (Black)',
    'Tombow Mono Dust Catch Eraser',
    'Tombow Mono Eraser',
    'Seed Clear Eraser',
    'Kokuyo Standard LS',
    'Kokuyo Hakoake 2 Way Cutters',
    'Uni Mechanical Pencil Refill High Uni 0.5 HB',
    'Uni Mechanical Pencil Refill High Uni 0.5 2B',
    'Kutsuwa Folding Ruler Black',
    'Tombow Mono Air Correction Tape',
    'Kokuyo Bread Pen Case',
    'Kokuyo Naminami Pen Case',
    'Sonic Kakusta',
    'ポッチャマ　の　ペン'
];

let PRODUCT_TYPES = [
    'pens',
    'pens',
    'pens',
    'pens',
    'pens',
    'pens',
    'pens',
    'pens',
    'pens',
    'pens',
    'pens',
    'pencils',
    'pencils',
    'pencils',
    'pencils',
    'notebooks',
    'notebooks',
    'notebooks',    
    'paper',
    'paper',
    'paper',
    'glue',
    'glue',
    'glue',
    'erasers',
    'erasers',
    'erasers',
    'erasers',
    'erasers',
    'scissors',
    'scissors',
    'accessories',
    'accessories',
    'accessories',
    'accessories',
    'pencil-cases',
    'pencil-cases',
    'pencil-cases',
    'penguins'
];